# Generated by Django 5.1.5 on 2025-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
