# Generated by Django 5.1.5 on 2025-01-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_company_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='telegram_id',
            new_name='chat_id',
        ),
    ]
