# Generated by Django 5.1.5 on 2025-01-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_telegram_id_company_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='chat_id',
            new_name='tg_id',
        ),
        migrations.DeleteModel(
            name='CompanyList',
        ),
    ]
