# Generated by Django 5.1.5 on 2025-01-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_chat_id_company_tg_id_delete_companylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
