# Generated by Django 5.1.5 on 2025-01-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_company_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tg_id',
        ),
    ]
