# Generated by Django 5.1.5 on 2025-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_company_chat_id_remove_company_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
