# Generated by Django 5.1.5 on 2025-01-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_company_chat_id_company_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tg_id',
        ),
    ]
